# Generated by Django 3.1.3 on 2020-12-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='FilesUpload',
        ),
    ]
